# Site
repository: kamesh-se/kamesh-se.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kamesh
title: Lead engineer
email: kamesh.chandran@gmail.com
website: kamesh-se.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kamesh-se
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kameshchandran
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1-sticker.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kamesh and I have 14+ years of versatile experience in Lead Engineering, Data Center, Order Management, reseller, Banking  (Merchant and Customer banking portal), Design & Development of the portal, REST-Based servicing application (Middleware/Micro Service application).

  Presently associated with Equinix, Singapore as Senior Staff Engineer (Lead engineer). The attached resume will give you the details of my background. I am confident that the experience you will find outlined therein will be valuable to your firm. 
  
#I am most skilled in: <mark>Data</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Equinix Customer Portal
        link: customerportal.equinix.com
        # link_text: Project Website
        caption: December 2016 - Present
        #additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
            Equinix Customer portal provides interconnections between or same customers and data center facilty services. Equinix data centers presence is all the metros close to business centers this enables the customer to interconnect seemlessly with less latency and secured.
        description: | # this will include new lines to allow paragraphs
         Modules:
         - Predicting the users actions based on attachement. Mdles like 
      - layout: left
        title: FIS (Fidility Informations Solution)
        link: fis.com
        # link_text: boringcompany.com
        sub_title: Technial Lead Engineer
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teh University of Texas, Exections Educations
        caption: 2019 - 2020
        sub_title: PGP (Artifical intelligence and Machine learning)
        quote: >
          The University of Texas at Austin, shortened to UT Austin, UT, or Texas, is a public research university in Austin, Texas and the flagship institution of the University of Texas System. 
        description: | # this will include new lines to allow paragraphs
          I learn to create and manage machine learning models during the modern way of online education—the basics skill like cleansing the data for model prediction, PCA, and Feature engineering. I learned to organize the data and understand the business use case to predict the models.  

          
      - layout: left
        title: JJ College of engineering (Affiliated to Anna University)
        caption: 2003 - 2006
        sub_title: BSc Computer Science
        quote: >
           	J.J. Educational, Health & Charitable Trust has been established in the year 1994 with a vision to create, educational facilities in general and technical institutions in particular, to the socially educationally and economically under privileged youth from rural areas in and around Tiruchirappalli.
        description: | # this will include new lines to allow paragraphs
          During my time at College I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *College Developer Community* taking on roles such as arranging hacking sessions for joniors *Hackathon Organizer* and *Caltural Event Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and software engineering some of my other interests and hobbies are:
      - Running
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
