# Site
repository: kamesh-se/kamesh-se.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kamesh
title: Lead engineer
email: kamesh.chandran@gmail.com
website: kamesh-se.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: kamesh-se
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kameshchandran
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1-sticker.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kamesh and I have 14+ years of versatile experience in Lead Engineering, Data Center, Order Management, reseller, Banking  (Merchant and Customer banking portal), Design & Development of the portal, REST-Based servicing application (Middleware/Micro Service application).

  Presently associated with Equinix, Singapore as Senior Staff Engineer (Lead engineer). The attached resume will give you the details of my background. I am confident that the experience you will find outlined therein will be valuable to your firm.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Equinix Customer Portal
        link: customerportal.equinix.com
        caption: December 2016 - Present
        quote: >
          Equinix Customer portal provides interconnections between or same customers and data center facility services. Equinix data centers presence is all the metros close to business centers this enables the customer to interconnect seamlessly with less latency and secured.
        description: | # this will include new lines to allow paragraphs
          I was 
          Modules worked:
          - Smart Discovery - Discovering the user actions based on users attachment or description. Based attachment content or descriptions the ML model will recommend orders type and pre populate the necessary details. 
          - Order Recommendation - This ML models recommend the user to place the connected orders based on users frequent action. ML model allows reduce number click and predicts the dependent orders. 
          - Enterprise Search Engine - Search is permission drive search engine, this allow the user to multilingual search query to find relevant information's. Relevancy and racking is designed based on business domain fields to provide seamless user experience. Data cleansing and engineered to solve the latency and speedy response.
          - Unified Notifications service - Unified notification message services with services like firebase, MS teams, Azure queue, SMS, and email
          - Interconnection LOA management - LOA process helps is a approval process which allow to establish connection between two customer. 
      - layout: left
        title: FIS (Fidelity information's Solution)
        link: fis.com
        sub_title: Technical Lead Engineer
        caption: November 2017 - Present
        quote: >
          FIS stays ahead of how the world is evolving to power businesses, across merchants, banking and capital markets, to outpace today’s fast-changing competitive landscape and help our clients run, grow and achieve more for their business. 
        description: | # this will include new lines to allow paragraphs
          Company need banking solutions online facilitate the customer to check the balance and make payments. I was lead engineer to provide generic solutions for merchant and customer to view the transaction. This will help the FIS Customer to get the out of the box solutions with white labeling option.
          Modules:
          - Aadhaar based KYC approval for customer - Creating back account based on aadhaar mobile number and finger print solutions to create a back account. 
          - Merchant Portal - Facilitates mPOS device association with seller. This portal provides seller to manage successful transactions and refunds. Solution is based on <mark>Angular JS<mark> as single page applications backed by middleware technology Spring 4.x, <mark>Java 8<mark> and Nginx

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Texas, Executions Educations
        caption: 2019 - 2020
        sub_title: PGP (Artificial intelligence and Machine learning)
        quote: >
          The University of Texas at Austin, shortened to UT Austin, UT, or Texas, is a public research university in Austin, Texas and the flagship institution of the University of Texas System.
        description: | # this will include new lines to allow paragraphs
          I learn to create and manage machine learning models during the modern way of online education—the basics skill like cleansing the data for model prediction, PCA, and Feature engineering. I learned to organize the data and understand the business use case to predict the models.
      - layout: left
        title: JJ College of engineering (Affiliated to Anna University)
        caption: 2003 - 2006
        sub_title: BSc Computer Science
        quote: JJ Colleger of Engineering 

        description: | # this will include new lines to allow paragraphs
          During my time at College I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.>

          I spent a lot of my free time as a committee member of the *College Developer Community* taking on roles such as arranging hacking sessions for juniors *Hackathon Organizer* and *Cultural Event Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and software engineering some of my other interests and hobbies are: >
      - Running
      - Gaming
      - Blogs 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-ta
