# Site
repository: kamesh-se/kamesh-se.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kamesh
title: Lead engineer
email: kamesh.chandran@gmail.com
website: kamesh-se.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: kamesh-se
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kameshchandran
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1-sticker.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kamesh and I have 14+ years of versatile experience in Lead Engineering, Data Center, Order Management, reseller, Banking  (Merchant and Customer banking portal), Design & Development of the portal, REST-Based servicing application (Middleware/Micro Service application).

  Presently associated with Equinix, Singapore as Senior Staff Engineer (Lead engineer). The attached resume will give you the details of my background. I am confident that the experience you will find outlined therein will be valuable to your firm. 
  

  **Core Competencies**:
  - Data Architect/Engineer 
  - API Evangelist/Solution Architect
  - Problem Solving 
  - Teamwork 
  - Engineering Service Lead
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Equinix Customer Portal
        link: customerportal.equinix.com
        caption: December 2016 - Present
        quote: >
          Equinix's single global platform helped digital leaders stay out front for more than 20 years. Interconnect your digital infrastructure to scale with agility, leveraging leading enterprises and service providers in ecosystems that multiply value for all. At Equinix, we see every day as a fresh opportunity to help you fast track your digital advantage.
        description: | # this will include new lines to allow paragraphs
          Equinix Customer portal provides interconnections between digital enterprises. The customer portal can have data services offered and provides all the aftermarket facilities like billing in a single unified platform. Customers can utilize multiple channels, web, mobile, and API for direct automation. Organizations give me the most challenging data center industrial problem to solve with my current <mark>5+ years</mark> association.


          **Modules Lead and contributed**:
          - Enterprise Search Engine - Search is a permission drive search engine; this allows the user to multilingual search queries to find relevant information. Relevancy and racking are designed based on business domain fields to provide a seamless user experience. Solutions is based on Kafka Messages, Spark Streaming, Spring 4.x and Elastic search
          - Unified Notifications service - Unified notification message services with services like firebase, MS teams, Azure queue, SMS, and email. Solutions is based on Kafka Messaging, Azure queue, Spring 4.x and Third party API interfaces.
          - Interconnection LOA management - The LOA process helps an approval process that allows establishing connection between two customers. 
          - Machine learnings projects
            - Smart Discovery - Discovering the user actions based on users' attachment or description. Based on attachment content or request descriptions, the ML model will recommend order types and pre-populate the necessary details. 
            - Order Recommendation - This ML models recommend that the user place the connected orders based on frequent action. ML model allows to reduce the number of clicks and predicts the dependent orders. 
      - layout: left
        title: FIS (Fidelity information's Solution)
        link: fisglobal.com
        sub_title: Technical Lead Engineer
        caption: July 2014 - December 2015
        quote: >
          FIS stays ahead of how the world is evolving to power businesses, across merchants, banking and capital markets, to outpace today’s fast-changing competitive landscape and help our clients run, grow and achieve more for their business. 
        description: | # this will include new lines to allow paragraphs
          The organization needs banking solutions online to facilitate the buyer and seller to check the balance and make payments. I was the lead engineer to provide generic solutions for merchants and customers to view and manage any transaction life cycle. Portal will help the FIS Customer get them out of the box solutions with a white labeling option. The organization has given me multiple opportunities to mature my industrial banking experience in a short period of <mark>1.6 years</mark>.           
          
          **Modules Lead and contributed**:
          - Aadhaar based KYC approval for customer - Creating back account based on aadhaar mobile number and finger print solutions to create a back account. 
          - Merchant Portal - Facilitates mPOS device association with seller. This portal provides seller to manage successful transactions and refunds. Solution is based on <mark>Angular JS</mark> as single page applications backed by middleware technology <mark>Spring 4.x, Java 8 and Nginx</mark>
          - Prepaid Customer Portal (Mobile wallet)- Facilitates mPOS device association with seller. This portal provides seller to manage successful transactions and refunds. Solution is based on <mark>Angular JS</mark> as single page applications backed by middleware technology <mark>Spring 4.x, Java 8 and Nginx</mark>
      - layout: left
        title: HTSL (Honeywell Technology Solutions Lab)
        link: https://aerospace.honeywell.com/
        sub_title: Technical Lead Engineer
        caption: July 2006 - April 2014
        quote: >
         Honeywell Technology Solutions Lab Private Limited is a computer software company
        description: | # this will include new lines to allow paragraphs
          Portal has the ability to airplane product orders and manages the warranty for Honeywell aerospace-related offerings. Portal facilitates engineers to download engine technical documentation based. Customers will have the option to make payment for the rented airplane engines or services offerings. During <mark>7.6 years</mark> of the journey, organizations have given me multiple opportunities to mature aerospace industrial experience. I played various roles from time to time for 16 months as an on-site coordinator, five years as a technical lead with a team size of 10 members, two years as an engineer, and six months as an intern trainee. During my organizations' journey, I was an active member in evaluating technology and innovative solutions. 
         
          
          **Modules Lead and contributed**:
          - Aerospace Portal - A leading web portal for Honeywell Aerospace customer and Customer support representatives to place orders, collate information on the order, download the technical document, and search for field service engineer and support locator. Solutions based on <mark>Websphere Portal 7, Sprint Portlets and Generic portlets</mark>. 
          - SHARED Portal Migration - Enable Honeywell’s airline customers to access value-added aftermarket service for their MRO requirements through migration of SHARED system functionality to the MyAerospace portal. Solutions is based on Spring 3.x, MyBatis, Ajax and Websphere portal server.
          - Plymouth Migration - Reselling portal enabling customers & employees to search & browse through the catalog, add to cart and process with placing an order. Solution is based on SAP ECC eSelling, XCM, NWDS.
          - ATR Catalog - Enable internal Honeywell’s sales rep to access ATR catalog form any mobile device. This allows configuring and downloading the catalog online and persists them on the devices. Especially when they are in the Aero show conference 
          - Other Projects
            - HSCE - Honeywell Health and Safety system Portal
            - Teardown Management system - Barcode generation, for comparing LCD productions for Honeywell Patterns
            - HonBoard - Online whiteboard solutions like "Miro"
            - Catalogic - IPad Applications for Aerospace Catalog for sales and marketing.
            - Integrated Supply chain - <mark>SAP Enterprise Portal</mark> Solution based for Supply chain management. 
            - Single Singe On Integration - using saml defining authorizations and authentications between multiple systems

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Texas, Executions Educations
        caption: 2019 - 2020
        sub_title: PGP (Artificial intelligence and Machine learning)
        link: https://eportfolio.greatlearning.in/kamesh
        quote: >
          The University of Texas at Austin, shortened to UT Austin, UT, or Texas, is a public research university in Austin, Texas and the flagship institution of the University of Texas System.
        description: | # this will include new lines to allow paragraphs
          I learn to create and manage machine learning models during the modern way of online education—the basics skill like cleansing the data for model prediction, PCA, and Feature engineering. I learned to organize the data and understand the business use case to predict the models.
      - layout: left
        title: JJ College of engineering (Affiliated to Anna University)
        caption: 2003 - 2006
        sub_title: BSc Computer Science
        quote: JJ Colleger of Engineering 

        description: | # this will include new lines to allow paragraphs
          During my time at College I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *College Developer Community* taking on roles such as arranging hacking sessions for juniors *Hackathon Organizer* and *Cultural Event Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and software engineering some of my other interests and hobbies are: >
      - Running
      - Gaming
      - Blogs 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-ta
